-- age_category
INSERT INTO age_category (category_id, name, min_age, max_age) VALUES (1, 'U12', 0, 11);
INSERT INTO age_category (category_id, name, min_age, max_age) VALUES (2, 'U14', 12, 13);
INSERT INTO age_category (category_id, name, min_age, max_age) VALUES (3, 'U16', 14, 15);
INSERT INTO age_category (category_id, name, min_age, max_age) VALUES (4, 'Senior', 16, 99);

-- team
INSERT INTO team (team_id, name, country, member_count) VALUES (1, 'Beneš a.s.', 'Severní Korea', 15);
INSERT INTO team (team_id, name, country, member_count) VALUES (2, 'Kratochvíl k.s.', 'Francie', 9);
INSERT INTO team (team_id, name, country, member_count) VALUES (3, 'Matoušek Bureš s.r.o.', 'Seychely', 25);
INSERT INTO team (team_id, name, country, member_count) VALUES (4, 'Matoušek', 'Gambie', 23);
INSERT INTO team (team_id, name, country, member_count) VALUES (5, 'Kovářová s.r.o.', 'Svatá Lucie', 22);
INSERT INTO team (team_id, name, country, member_count) VALUES (6, 'Říha', 'Guyana', 16);

-- discipline
INSERT INTO discipline (discipline_id, name) VALUES (1, 'Butterfly');
INSERT INTO discipline (discipline_id, name) VALUES (2, 'Freestyle');
INSERT INTO discipline (discipline_id, name) VALUES (3, 'Backstroke');
INSERT INTO discipline (discipline_id, name) VALUES (4, 'Breaststroke');
INSERT INTO discipline (discipline_id, name) VALUES (5, 'IM');

-- race_events
INSERT INTO race_events (event_id, name, event_date, start_time, location, price) VALUES (1, 'Hanušovice Swim Meet #1', '2026-01-26', '23:07:24', 'Hrob', 254);
INSERT INTO race_events (event_id, name, event_date, start_time, location, price) VALUES (2, 'Fulnek Swim Meet #2', '2025-12-03', '21:45:34', 'Třeboň', 708);
INSERT INTO race_events (event_id, name, event_date, start_time, location, price) VALUES (3, 'Jihlava Swim Meet #3', '2026-01-24', '06:20:40', 'Raspenava', 239);
INSERT INTO race_events (event_id, name, event_date, start_time, location, price) VALUES (4, 'Rotava Swim Meet #4', '2026-01-05', '21:14:43', 'Husinec', 754);

-- coach
INSERT INTO coach (coach_id, team_id, first_name, surname, birthdate, telephone, email) VALUES (1, 1, 'Jindřiška', 'Mašek', '1969-05-01', '00420 723 180 051', 'maskovajana@example.net');
INSERT INTO coach (coach_id, team_id, first_name, surname, birthdate, telephone, email) VALUES (2, 2, 'Magdaléna', 'Bartošová', '1994-08-29', '00420 797 139 089', 'soukuprichard@example.net');
INSERT INTO coach (coach_id, team_id, first_name, surname, birthdate, telephone, email) VALUES (3, 3, 'Bohumír', 'Musil', '1975-05-14', '+420 608 313 998', 'fhorvath@example.org');
INSERT INTO coach (coach_id, team_id, first_name, surname, birthdate, telephone, email) VALUES (4, 4, 'Miluše', 'Hájková', '1987-10-25', '+420 605 913 279', 'ostepankova@example.org');
INSERT INTO coach (coach_id, team_id, first_name, surname, birthdate, telephone, email) VALUES (5, 5, 'Mikuláš', 'Vacková', '1979-05-16', '00420 703 061 870', 'horacekales@example.com');
INSERT INTO coach (coach_id, team_id, first_name, surname, birthdate, telephone, email) VALUES (6, 6, 'Žaneta', 'Konečná', '1974-06-29', '+420 738 541 215', 'horvathalexandr@example.com');

-- swimmer
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (1, 'Alexandra', 'Lišková', '2011-04-01', 133, 40, 4, 1);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (2, 'Iva', 'Müller', '2006-01-11', 194, 73, 2, 2);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (3, 'Mikuláš', 'Beránek', '2004-04-28', 155, 80, 1, 5);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (4, 'Olivie', 'Beneš', '2006-02-12', 187, 72, 4, 2);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (5, 'Pavel', 'Vacek', '2016-11-29', 150, 79, 3, 1);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (6, 'Jitka', 'Brožová', '2005-06-23', 165, 44, 4, 3);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (7, 'Soňa', 'Kopecká', '2005-08-16', 143, 40, 2, 3);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (8, 'Olivie', 'Navrátil', '2012-03-25', 175, 89, 4, 1);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (9, 'Drahomíra', 'Dostál', '2013-10-27', 163, 86, 3, 5);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (10, 'Květoslava', 'Kašparová', '2013-05-25', 188, 69, 1, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (11, 'Marta', 'Kolář', '2012-05-25', 140, 70, 1, 4);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (12, 'Kamil', 'Janda', '2016-01-09', 176, 71, 3, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (13, 'Ondřej', 'Krausová', '2016-08-16', 138, 37, 2, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (14, 'Bohumír', 'Musil', '2013-10-22', 140, 89, 2, 3);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (15, 'Milada', 'Tichá', '2008-09-12', 178, 52, 2, 1);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (16, 'Vladimír', 'Králová', '2010-04-16', 176, 45, 4, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (17, 'Bohuslav', 'Čermák', '2007-04-08', 156, 77, 3, 3);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (18, 'Oldřich', 'Němcová', '2012-07-14', 139, 73, 3, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (19, 'Danuše', 'Horáček', '2012-05-30', 161, 45, 2, 5);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (20, 'Zikmund', 'Pavlíček', '2005-01-04', 164, 94, 4, 4);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (21, 'Kristýna', 'Sedláčková', '2012-08-01', 171, 88, 2, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (22, 'Daniel', 'Macháček', '2015-11-27', 134, 86, 1, 2);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (23, 'Samuel', 'Marková', '2014-09-23', 164, 39, 3, 4);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (24, 'Mária', 'Kratochvíl', '2015-02-18', 170, 48, 2, 5);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (25, 'Alena', 'Říhová', '2011-09-22', 188, 44, 4, 4);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (26, 'Miloš', 'Toman', '2007-01-24', 161, 82, 3, 2);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (27, 'Zora', 'Havlíčková', '2017-08-11', 184, 92, 3, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (28, 'Renata', 'Vávrová', '2007-03-18', 158, 43, 4, 3);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (29, 'Květa', 'Sedláková', '2017-07-13', 136, 90, 4, 1);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (30, 'Luděk', 'Hájek', '2004-02-18', 150, 85, 1, 2);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (31, 'Michael', 'Horák', '2006-01-16', 138, 59, 4, 5);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (32, 'Zdeňka', 'Benešová', '2005-04-24', 189, 68, 4, 5);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (33, 'Jitka', 'Kašparová', '2004-09-01', 131, 78, 3, 5);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (34, 'Felix', 'Bartoš', '2012-10-19', 198, 83, 1, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (35, 'Drahoslav', 'Jelínek', '2004-02-11', 173, 42, 3, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (36, 'Samuel', 'Fialová', '2009-06-04', 150, 64, 3, 4);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (37, 'Stanislava', 'Musilová', '2015-11-18', 163, 67, 1, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (38, 'Mária', 'Němec', '2014-03-25', 143, 90, 2, 5);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (39, 'Anastázie', 'Vaněk', '2008-12-26', 194, 73, 3, 6);
INSERT INTO swimmer (swimmer_id, first_name, surname, birthdate, height, weight, category_id, team_id) VALUES (40, 'Samuel', 'Král', '2007-04-12', 177, 83, 2, 2);

-- race
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (1, 2, '2026-02-02 01:20:31', 5, 1);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (2, 3, '2025-12-29 14:51:15', 4, 1);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (3, 1, '2026-03-11 17:31:00', 3, 3);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (4, 2, '2026-02-24 15:09:40', 1, 2);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (5, 1, '2025-12-05 16:55:38', 1, 4);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (6, 1, '2026-02-02 10:53:20', 5, 2);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (7, 2, '2026-01-05 22:40:08', 4, 2);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (8, 3, '2026-03-14 18:35:01', 5, 4);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (9, 2, '2025-12-17 12:09:27', 5, 2);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (10, 3, '2026-02-18 03:21:35', 4, 3);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (11, 4, '2025-11-29 13:02:51', 5, 4);
INSERT INTO race (race_id, event_id, race_start, discipline_id, category_id) VALUES (12, 1, '2025-12-22 08:03:51', 2, 2);

-- race_swimmer
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (5, 1);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (2, 11);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (5, 28);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (6, 2);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (10, 27);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (10, 36);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (11, 16);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (6, 13);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (2, 34);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (3, 17);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (3, 26);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (12, 38);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (5, 32);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (1, 10);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (7, 14);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (1, 37);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (12, 13);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (5, 16);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (9, 14);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (5, 25);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (12, 40);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (1, 3);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (7, 7);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (10, 33);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (1, 30);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (11, 32);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (9, 7);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (11, 4);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (6, 38);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (10, 17);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (8, 29);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (11, 25);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (2, 22);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (10, 35);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (4, 13);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (3, 23);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (6, 40);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (7, 2);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (6, 15);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (5, 4);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (12, 19);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (9, 2);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (4, 15);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (4, 24);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (11, 29);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (3, 9);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (5, 6);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (12, 21);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (3, 18);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (8, 8);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (1, 11);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (2, 10);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (3, 39);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (11, 31);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (2, 37);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (4, 19);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (2, 3);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (5, 20);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (12, 7);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (6, 21);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (1, 34);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (4, 21);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (10, 9);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (11, 8);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (6, 14);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (7, 13);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (4, 14);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (7, 40);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (9, 13);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (3, 27);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (11, 28);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (6, 7);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (12, 2);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (7, 15);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (4, 7);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (7, 24);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (5, 8);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (9, 15);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (9, 24);
INSERT INTO race_swimmer (race_id, swimmer_id) VALUES (1, 22);
